services:
  - type: web
    name: seva
    runtime: node
    buildCommand: npm install && npm run install:client && npm run build:client
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
