services:
  - type: web
    name: seva
    runtime: node
    buildCommand: npm install && npm run install:client && npm run build:client
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GMAIL_CLIENT_ID
        sync: false
      - key: GMAIL_CLIENT_SECRET
        sync: false
      - key: GMAIL_REFRESH_TOKEN
        sync: false
      - key: GMAIL_USER
        sync: false
